### ISSUE TITLE
update to release cpp driver?

### ISSUE THREAD

**Issue by ethrbunny** [aparkhomenko/php-cassandra#10]
The 'deprecated' branch is several versions out of date.

**Comment by aparkhomenko** [comment]
I don't get your question

**Comment by ethrbunny** [comment]
Your configure/make relies on files that are only available in the 'deprecated' branch of the datastax/cpp-driver. Just wondering if you have plans to update your include files and such to the release (1.0.0) build.

**Comment by aparkhomenko** [comment]
Yes, I've got plans to update. I can't tell you when, but I'm working on a new version.

**Comment by mcd-php** [comment]
+1 

When do you plan to upgrade to the newest version ? What has to be done, how hard is it, can it be accomplished w/o deep C++ knowledge ?

Did you notify the original authors of Cassandra C++ driver about your work ? Did you try to give the project to somebody else if you are not going support it ?

Are you aware of the http://www.swig.org/ project ? It makes easier to connect code in 'native' languages to interpreted ones.
