### ISSUE TITLE
CqlResult::get returns NULL on counter field

### ISSUE THREAD

**Issue by janossuranyi** [aparkhomenko/php-cassandra#12]
Hello!

I'm wondering is there any special thing to get a counter value from a CqlResult?
I did the following query:

cqlsh:xxx> select * from post_stat where id = 16642;

 id    | click | impression | rawclick
-------+-------+------------+----------
 16642 |     0 |       3842 |        0

Same query in php-cassandra returns NULL for all counter types:

rowCount: 1
Id:int(16642)
Impression:NULL

Regards
Janos

**Comment by aparkhomenko** [comment]
Fixed, please check on your side.

**Comment by janossuranyi** [comment]
Work like a charm !!

Thank you very, very much !
